---
- hosts: all
  become: true   # (optional, but usually needed to install packages)
  tasks:
    - name: Install tmux package
      apt:
        name: tmux
        state: present
        update_cache: yes

