---
- hosts: all
  become: true 
  tasks:
    - name: Install tmux package
      apt:
        name: tmux
        state: present
        update_cache: yes
    - name: Install git package
      apt:
        name : git
        state: present
        update_cache: yes

